<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/register" method="post">
              <div class="form-group">
                <input name="name" 
                value="<?= isset($_GET['name']) ? $_GET['name'] : '' ?>" type="text" class="form-control" placeholder="Nome">
              </div>
              
              <div class="form-group">
                <input name="email" value="<?= isset($_GET['email']) ? $_GET['email'] : '' ?>" type="text" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input name="password" value="<?= isset($_GET['password']) ? $_GET['password'] : '' ?>" type="password" class="form-control" placeholder="Senha">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>

              <?php if(isset($_GET['register']) && $_GET['register'] == 'invalid') {?>
                <div class="mt-4">
                  <span class="text-danger">Invalid:)</span>
                </div>
              <?php } ?>

              <?php if(isset($_GET['register']) && $_GET['register'] == 'exists') {?>
                <div class="mt-4">
                  <span class="text-danger">Already exists:)</span>
                </div>
              <?php } ?>

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  