<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/logout">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">Nome do Usuário</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->tweetsCount ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->followCount ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->followerCount ?>
							</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form action="/tweet" method="post">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach($this->view->tweets as $tweet) {?>
				<div class="row tweet">
					<div class="col">
						<p><strong><?= $tweet['name'] ?></strong> <span class="text text-muted"><small><?= $tweet['tweet_date'] ?></small></span></p>
						<p><?= $tweet['tweet'] ?></p>

						<br />

						<?php if($tweet['user_id'] === $_SESSION['id']) { ?>
							<form action="/remove" method="post">
								<div class="col d-flex justify-content-end">
									<input name="tweet_id" value="<?= $tweet['id'] ?>" type="hidden">
									<button type="submit" class="btn btn-danger"><small>Remover</small></button>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>

			<!-- <div class="row tweet">
				<div class="col">
					<p><strong>Nome do Usuário</strong> <span class="text text-muted">- data tweet</span></p>
					<p>Conteúdo do tweet</p>

					<br />
					<form>
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger"><small>Remover</small></button>
						</div>
					</form>		
				</div>
			</div> -->


		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/following" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>