<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Layout_2</title>
</head>
<body>
  <header>
    <h1>Layout_2_Header</h1>
  </header>
  <hr>

  <h1>Layout_2_Content</h1>
  <?= $this->content() ?>

  <hr>
  <footer>
    <h1>Layout_2_Footer</h1>
  </footer>
</body>
</html>
